### PR TITLE
make dev mode work with webpack 5

### PR DESCRIPTION
**Pull request by angelo-v**

### CODE REVIEW

**Comment by bourgeoa** [comment]
The CI fail relate to solid-logic/rdflib types.
- The latest solid-logic@1.3.9 is a partial solution, there remain a new missing type `whether`
- resolved with latest  rdflib@2.2.10-4fa7e876

**Comment by angelo-v** [comment]
Hey @bourgeoa the CI problems you mention are not part of my PR but actually introduced by yourself with the dependency upgrade in commit 8ac29ff. 

This is not meant to be finger pointing, I really appreciate your hard work on SolidOS. But since you seem not to have been aware of it since 12 days, there is something wrong with our process I think and we need to talk about ways to prevent broken mainline in the future. It is quite obstructive if one just want to provide a small fix in a PR. Perhaps we can talk about it on wednesday.

The way to go here in my opinion, is to fix main first, then rebase and merge this branch.

**Comment by bourgeoa** [comment]
> But since you seem not to have been aware of it since 12 days, there is something wrong with our process I think and we need to talk about ways to prevent broken mainline in the future. It is quite obstructive if one just want to provide a small fix in a PR. Perhaps we can talk about it on wednesday.

Yes I know it is not part of your PR and I explained where it came from, and yes Wednesday meeting it is a good place to review the process.
Some comment : 
- I made a mistake locally experimenting with `typescript-transpile-only` see https://gitter.im/solid/solidos?at=619772c0abdd6644e3931f75 and I did not understand that it was remaining as a pre-processor of tsc.
- we must review that CI and bulk update with solidos/scripts/release are and stay equivalent. This is not the case for example with rdflib :
  - CI used `npm ci && npm run build && npm run build:types && npm run build:browser && npm run build:esm`
  - while the solidos/release always use only `npm publish` for all repos
- I remember the same problem did arise with solid-ui with `npm run doc` that is not included in `npm run build`

Is there somewhere a document referencing the scripts structure and CI  ?
The actual scripts and CI where only partially updated when moving from Jekill to Github Actions, and with adding CI including publish

**Comment by bourgeoa** [comment]
@aveltens @SharonStrats @timea 
Good for review
CI succeed with solid-ui@2.2.12, rdflib@2.2.12 includes typescripts d.ts and solid-logic@1.3.10 removed typescript hack

**Comment by timea** [comment]
I think you tagged the wrong person :)

**Comment by bourgeoa** [comment]
Thanks

Le dim. 21 nov. 2021 à 22:02, Timea Kiss ***@***.***> a
écrit :

> I think you tagged the wrong person :)
>

**Review by SharonStrats — COMMENTED** [review]
Awesome!  Thank you :)

**Pull request merged**
